<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Pago', 'doctrine');

/**
 * BasePago
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_pago
 * @property integer $id_solicitud
 * @property date $fecha
 * @property integer $monto
 * @property SolicitudLicencia $SolicitudLicencia
 * 
 * @method integer           getIdPago()            Returns the current record's "id_pago" value
 * @method integer           getIdSolicitud()       Returns the current record's "id_solicitud" value
 * @method date              getFecha()             Returns the current record's "fecha" value
 * @method integer           getMonto()             Returns the current record's "monto" value
 * @method SolicitudLicencia getSolicitudLicencia() Returns the current record's "SolicitudLicencia" value
 * @method Pago              setIdPago()            Sets the current record's "id_pago" value
 * @method Pago              setIdSolicitud()       Sets the current record's "id_solicitud" value
 * @method Pago              setFecha()             Sets the current record's "fecha" value
 * @method Pago              setMonto()             Sets the current record's "monto" value
 * @method Pago              setSolicitudLicencia() Sets the current record's "SolicitudLicencia" value
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePago extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pago');
        $this->hasColumn('id_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_solicitud', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('monto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SolicitudLicencia', array(
             'local' => 'id_solicitud',
             'foreign' => 'id_solicitud'));
    }
}