<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClaseAnterior', 'doctrine');

/**
 * BaseClaseAnterior
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_solicitud
 * @property integer $id_tipo_licencia
 * @property TipoLicencia $TipoLicencia
 * @property SolicitudLicencia $SolicitudLicencia
 * 
 * @method integer           getIdSolicitud()       Returns the current record's "id_solicitud" value
 * @method integer           getIdTipoLicencia()    Returns the current record's "id_tipo_licencia" value
 * @method TipoLicencia      getTipoLicencia()      Returns the current record's "TipoLicencia" value
 * @method SolicitudLicencia getSolicitudLicencia() Returns the current record's "SolicitudLicencia" value
 * @method ClaseAnterior     setIdSolicitud()       Sets the current record's "id_solicitud" value
 * @method ClaseAnterior     setIdTipoLicencia()    Sets the current record's "id_tipo_licencia" value
 * @method ClaseAnterior     setTipoLicencia()      Sets the current record's "TipoLicencia" value
 * @method ClaseAnterior     setSolicitudLicencia() Sets the current record's "SolicitudLicencia" value
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClaseAnterior extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clase_anterior');
        $this->hasColumn('id_solicitud', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_licencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoLicencia', array(
             'local' => 'id_tipo_licencia',
             'foreign' => 'id_tipo_licencia'));

        $this->hasOne('SolicitudLicencia', array(
             'local' => 'id_solicitud',
             'foreign' => 'id_solicitud'));
    }
}