<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SolicitudLicencia', 'doctrine');

/**
 * BaseSolicitudLicencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_solicitud
 * @property integer $id_tramite
 * @property string $rut
 * @property integer $user_id
 * @property integer $id_pago
 * @property integer $id_hora
 * @property integer $id_tipo_licencia
 * @property string $estado
 * @property date $fecha_ultimo_control
 * @property date $fecha_control
 * @property integer $restriccion
 * @property string $comuna_anterior
 * @property integer $porta_licencia
 * @property string $motivo_no_porta_licencia
 * @property integer $es_donante
 * @property TipoLicencia $TipoLicencia
 * @property Tramite $Tramite
 * @property Hora $Hora
 * @property sfGuardUser $User
 * @property Pago $Pago
 * @property Doctrine_Collection $ClaseAnterior
 * 
 * @method integer             getIdSolicitud()              Returns the current record's "id_solicitud" value
 * @method integer             getIdTramite()                Returns the current record's "id_tramite" value
 * @method string              getRut()                      Returns the current record's "rut" value
 * @method integer             getUserId()                   Returns the current record's "user_id" value
 * @method integer             getIdPago()                   Returns the current record's "id_pago" value
 * @method integer             getIdHora()                   Returns the current record's "id_hora" value
 * @method integer             getIdTipoLicencia()           Returns the current record's "id_tipo_licencia" value
 * @method string              getEstado()                   Returns the current record's "estado" value
 * @method date                getFechaUltimoControl()       Returns the current record's "fecha_ultimo_control" value
 * @method date                getFechaControl()             Returns the current record's "fecha_control" value
 * @method integer             getRestriccion()              Returns the current record's "restriccion" value
 * @method string              getComunaAnterior()           Returns the current record's "comuna_anterior" value
 * @method integer             getPortaLicencia()            Returns the current record's "porta_licencia" value
 * @method string              getMotivoNoPortaLicencia()    Returns the current record's "motivo_no_porta_licencia" value
 * @method integer             getEsDonante()                Returns the current record's "es_donante" value
 * @method TipoLicencia        getTipoLicencia()             Returns the current record's "TipoLicencia" value
 * @method Tramite             getTramite()                  Returns the current record's "Tramite" value
 * @method Hora                getHora()                     Returns the current record's "Hora" value
 * @method sfGuardUser         getUser()                     Returns the current record's "User" value
 * @method Pago                getPago()                     Returns the current record's "Pago" value
 * @method Doctrine_Collection getClaseAnterior()            Returns the current record's "ClaseAnterior" collection
 * @method SolicitudLicencia   setIdSolicitud()              Sets the current record's "id_solicitud" value
 * @method SolicitudLicencia   setIdTramite()                Sets the current record's "id_tramite" value
 * @method SolicitudLicencia   setRut()                      Sets the current record's "rut" value
 * @method SolicitudLicencia   setUserId()                   Sets the current record's "user_id" value
 * @method SolicitudLicencia   setIdPago()                   Sets the current record's "id_pago" value
 * @method SolicitudLicencia   setIdHora()                   Sets the current record's "id_hora" value
 * @method SolicitudLicencia   setIdTipoLicencia()           Sets the current record's "id_tipo_licencia" value
 * @method SolicitudLicencia   setEstado()                   Sets the current record's "estado" value
 * @method SolicitudLicencia   setFechaUltimoControl()       Sets the current record's "fecha_ultimo_control" value
 * @method SolicitudLicencia   setFechaControl()             Sets the current record's "fecha_control" value
 * @method SolicitudLicencia   setRestriccion()              Sets the current record's "restriccion" value
 * @method SolicitudLicencia   setComunaAnterior()           Sets the current record's "comuna_anterior" value
 * @method SolicitudLicencia   setPortaLicencia()            Sets the current record's "porta_licencia" value
 * @method SolicitudLicencia   setMotivoNoPortaLicencia()    Sets the current record's "motivo_no_porta_licencia" value
 * @method SolicitudLicencia   setEsDonante()                Sets the current record's "es_donante" value
 * @method SolicitudLicencia   setTipoLicencia()             Sets the current record's "TipoLicencia" value
 * @method SolicitudLicencia   setTramite()                  Sets the current record's "Tramite" value
 * @method SolicitudLicencia   setHora()                     Sets the current record's "Hora" value
 * @method SolicitudLicencia   setUser()                     Sets the current record's "User" value
 * @method SolicitudLicencia   setPago()                     Sets the current record's "Pago" value
 * @method SolicitudLicencia   setClaseAnterior()            Sets the current record's "ClaseAnterior" collection
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSolicitudLicencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('solicitud_licencia');
        $this->hasColumn('id_solicitud', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_tramite', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rut', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('id_pago', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_hora', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_licencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('fecha_ultimo_control', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_control', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('restriccion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('comuna_anterior', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('porta_licencia', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('motivo_no_porta_licencia', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('es_donante', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoLicencia', array(
             'local' => 'id_tipo_licencia',
             'foreign' => 'id_tipo_licencia'));

        $this->hasOne('Tramite', array(
             'local' => 'id_tramite',
             'foreign' => 'id_tramite'));

        $this->hasOne('Hora', array(
             'local' => 'id_hora',
             'foreign' => 'id_hora'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Pago', array(
             'local' => 'id_pago',
             'foreign' => 'id_pago'));

        $this->hasMany('ClaseAnterior', array(
             'local' => 'id_solicitud',
             'foreign' => 'id_solicitud'));
    }
}