<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Hora', 'doctrine');

/**
 * BaseHora
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_hora
 * @property integer $id_solicitud
 * @property date $fecha_hora
 * @property time $hora_ini
 * @property string $tipo
 * @property Doctrine_Collection $SolicitudLicencia
 * 
 * @method integer             getIdHora()            Returns the current record's "id_hora" value
 * @method integer             getIdSolicitud()       Returns the current record's "id_solicitud" value
 * @method date                getFechaHora()         Returns the current record's "fecha_hora" value
 * @method time                getHoraIni()           Returns the current record's "hora_ini" value
 * @method string              getTipo()              Returns the current record's "tipo" value
 * @method Doctrine_Collection getSolicitudLicencia() Returns the current record's "SolicitudLicencia" collection
 * @method Hora                setIdHora()            Sets the current record's "id_hora" value
 * @method Hora                setIdSolicitud()       Sets the current record's "id_solicitud" value
 * @method Hora                setFechaHora()         Sets the current record's "fecha_hora" value
 * @method Hora                setHoraIni()           Sets the current record's "hora_ini" value
 * @method Hora                setTipo()              Sets the current record's "tipo" value
 * @method Hora                setSolicitudLicencia() Sets the current record's "SolicitudLicencia" collection
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHora extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hora');
        $this->hasColumn('id_hora', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_solicitud', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_hora', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora_ini', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tipo', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SolicitudLicencia', array(
             'local' => 'id_hora',
             'foreign' => 'id_hora'));
    }
}