<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DiaNoLaboral', 'doctrine');

/**
 * BaseDiaNoLaboral
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_dia_no_laboral
 * @property integer $user_id
 * @property date $fecha_no_laboral
 * @property sfGuardUser $User
 * 
 * @method integer      getIdDiaNoLaboral()    Returns the current record's "id_dia_no_laboral" value
 * @method integer      getUserId()            Returns the current record's "user_id" value
 * @method date         getFechaNoLaboral()    Returns the current record's "fecha_no_laboral" value
 * @method sfGuardUser  getUser()              Returns the current record's "User" value
 * @method DiaNoLaboral setIdDiaNoLaboral()    Sets the current record's "id_dia_no_laboral" value
 * @method DiaNoLaboral setUserId()            Sets the current record's "user_id" value
 * @method DiaNoLaboral setFechaNoLaboral()    Sets the current record's "fecha_no_laboral" value
 * @method DiaNoLaboral setUser()              Sets the current record's "User" value
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiaNoLaboral extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dia_no_laboral');
        $this->hasColumn('id_dia_no_laboral', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('fecha_no_laboral', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}