<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConjuntoExamenes', 'doctrine');

/**
 * BaseConjuntoExamenes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tramite
 * @property integer $id_examen
 * @property integer $id_tipo_licencia
 * @property TipoLicencia $TipoLicencia
 * @property Tramite $Tramite
 * @property Examen $Examen
 * 
 * @method integer          getIdTramite()        Returns the current record's "id_tramite" value
 * @method integer          getIdExamen()         Returns the current record's "id_examen" value
 * @method integer          getIdTipoLicencia()   Returns the current record's "id_tipo_licencia" value
 * @method TipoLicencia     getTipoLicencia()     Returns the current record's "TipoLicencia" value
 * @method Tramite          getTramite()          Returns the current record's "Tramite" value
 * @method Examen           getExamen()           Returns the current record's "Examen" value
 * @method ConjuntoExamenes setIdTramite()        Sets the current record's "id_tramite" value
 * @method ConjuntoExamenes setIdExamen()         Sets the current record's "id_examen" value
 * @method ConjuntoExamenes setIdTipoLicencia()   Sets the current record's "id_tipo_licencia" value
 * @method ConjuntoExamenes setTipoLicencia()     Sets the current record's "TipoLicencia" value
 * @method ConjuntoExamenes setTramite()          Sets the current record's "Tramite" value
 * @method ConjuntoExamenes setExamen()           Sets the current record's "Examen" value
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConjuntoExamenes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conjunto_examenes');
        $this->hasColumn('id_tramite', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_examen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_licencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoLicencia', array(
             'local' => 'id_tipo_licencia',
             'foreign' => 'id_tipo_licencia'));

        $this->hasOne('Tramite', array(
             'local' => 'id_tramite',
             'foreign' => 'id_tramite'));

        $this->hasOne('Examen', array(
             'local' => 'id_examen',
             'foreign' => 'id_examen'));
    }
}