<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoLicencia', 'doctrine');

/**
 * BaseTipoLicencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tipo_licencia
 * @property string $nombre_tipo_licencia
 * @property string $descripcion_tipo_licencia
 * @property Doctrine_Collection $ConjuntoExamenes
 * @property Doctrine_Collection $ConjuntoRequisitos
 * @property Doctrine_Collection $ClaseAnterior
 * @property Doctrine_Collection $SolicitudLicencia
 * 
 * @method integer             getIdTipoLicencia()            Returns the current record's "id_tipo_licencia" value
 * @method string              getNombreTipoLicencia()        Returns the current record's "nombre_tipo_licencia" value
 * @method string              getDescripcionTipoLicencia()   Returns the current record's "descripcion_tipo_licencia" value
 * @method Doctrine_Collection getConjuntoExamenes()          Returns the current record's "ConjuntoExamenes" collection
 * @method Doctrine_Collection getConjuntoRequisitos()        Returns the current record's "ConjuntoRequisitos" collection
 * @method Doctrine_Collection getClaseAnterior()             Returns the current record's "ClaseAnterior" collection
 * @method Doctrine_Collection getSolicitudLicencia()         Returns the current record's "SolicitudLicencia" collection
 * @method TipoLicencia        setIdTipoLicencia()            Sets the current record's "id_tipo_licencia" value
 * @method TipoLicencia        setNombreTipoLicencia()        Sets the current record's "nombre_tipo_licencia" value
 * @method TipoLicencia        setDescripcionTipoLicencia()   Sets the current record's "descripcion_tipo_licencia" value
 * @method TipoLicencia        setConjuntoExamenes()          Sets the current record's "ConjuntoExamenes" collection
 * @method TipoLicencia        setConjuntoRequisitos()        Sets the current record's "ConjuntoRequisitos" collection
 * @method TipoLicencia        setClaseAnterior()             Sets the current record's "ClaseAnterior" collection
 * @method TipoLicencia        setSolicitudLicencia()         Sets the current record's "SolicitudLicencia" collection
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoLicencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_licencia');
        $this->hasColumn('id_tipo_licencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_tipo_licencia', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('descripcion_tipo_licencia', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ConjuntoExamenes', array(
             'local' => 'id_tipo_licencia',
             'foreign' => 'id_tipo_licencia'));

        $this->hasMany('ConjuntoRequisitos', array(
             'local' => 'id_tipo_licencia',
             'foreign' => 'id_tipo_licencia'));

        $this->hasMany('ClaseAnterior', array(
             'local' => 'id_tipo_licencia',
             'foreign' => 'id_tipo_licencia'));

        $this->hasMany('SolicitudLicencia', array(
             'local' => 'id_tipo_licencia',
             'foreign' => 'id_tipo_licencia'));
    }
}