<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Examen', 'doctrine');

/**
 * BaseExamen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_examen
 * @property string $nombre_examen
 * @property string $descripcion_examen
 * @property Doctrine_Collection $ConjuntoExamenes
 * 
 * @method integer             getIdExamen()           Returns the current record's "id_examen" value
 * @method string              getNombreExamen()       Returns the current record's "nombre_examen" value
 * @method string              getDescripcionExamen()  Returns the current record's "descripcion_examen" value
 * @method Doctrine_Collection getConjuntoExamenes()   Returns the current record's "ConjuntoExamenes" collection
 * @method Examen              setIdExamen()           Sets the current record's "id_examen" value
 * @method Examen              setNombreExamen()       Sets the current record's "nombre_examen" value
 * @method Examen              setDescripcionExamen()  Sets the current record's "descripcion_examen" value
 * @method Examen              setConjuntoExamenes()   Sets the current record's "ConjuntoExamenes" collection
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseExamen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('examen');
        $this->hasColumn('id_examen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_examen', 'string', 40, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('descripcion_examen', 'string', 512, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 512,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ConjuntoExamenes', array(
             'local' => 'id_examen',
             'foreign' => 'id_examen'));
    }
}