<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConjuntoRequisitos', 'doctrine');

/**
 * BaseConjuntoRequisitos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_requisito
 * @property integer $id_tramite
 * @property integer $id_tipo_licencia
 * @property TipoLicencia $TipoLicencia
 * @property Requisito $Requisito
 * @property Tramite $Tramite
 * 
 * @method integer            getIdRequisito()      Returns the current record's "id_requisito" value
 * @method integer            getIdTramite()        Returns the current record's "id_tramite" value
 * @method integer            getIdTipoLicencia()   Returns the current record's "id_tipo_licencia" value
 * @method TipoLicencia       getTipoLicencia()     Returns the current record's "TipoLicencia" value
 * @method Requisito          getRequisito()        Returns the current record's "Requisito" value
 * @method Tramite            getTramite()          Returns the current record's "Tramite" value
 * @method ConjuntoRequisitos setIdRequisito()      Sets the current record's "id_requisito" value
 * @method ConjuntoRequisitos setIdTramite()        Sets the current record's "id_tramite" value
 * @method ConjuntoRequisitos setIdTipoLicencia()   Sets the current record's "id_tipo_licencia" value
 * @method ConjuntoRequisitos setTipoLicencia()     Sets the current record's "TipoLicencia" value
 * @method ConjuntoRequisitos setRequisito()        Sets the current record's "Requisito" value
 * @method ConjuntoRequisitos setTramite()          Sets the current record's "Tramite" value
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseConjuntoRequisitos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conjunto_requisitos');
        $this->hasColumn('id_requisito', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tramite', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_licencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoLicencia', array(
             'local' => 'id_tipo_licencia',
             'foreign' => 'id_tipo_licencia'));

        $this->hasOne('Requisito', array(
             'local' => 'id_requisito',
             'foreign' => 'id_requisito'));

        $this->hasOne('Tramite', array(
             'local' => 'id_tramite',
             'foreign' => 'id_tramite'));
    }
}