<?php

/**
 * ClaseAnteriorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClaseAnteriorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClaseAnteriorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClaseAnterior');
    }
}