<?php

/**
 * ConjuntoRequisitosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConjuntoRequisitosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConjuntoRequisitosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConjuntoRequisitos');
    }
}