<?php

/**
 * ConjuntoExamenesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConjuntoExamenesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConjuntoExamenesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConjuntoExamenes');
    }
}