<?php

/**
 * DiaNoLaboralTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiaNoLaboralTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiaNoLaboralTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiaNoLaboral');
    }
}