<?php

/**
 * ExamenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Examen');
    }
}