<?php

/**
 * HoraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HoraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HoraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hora');
    }
}