<?php

/**
 * PagoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PagoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PagoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pago');
    }
}