<?php

/**
 * RequisitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequisitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequisitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Requisito');
    }
}