<?php

/**
 * SolicitudLicenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SolicitudLicenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SolicitudLicenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SolicitudLicencia');
    }
}