<?php

/**
 * SolicitudLicencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SolicitudLicencia extends BaseSolicitudLicencia
{
//    public function save(Doctrine_Connection $conn = null) {
//        if ($this->isNew()) {
////            $now = $this->getCreatedAt() ? $this->getDateTimeObject('created_at')->format('U') : time();
////            $this->setExpiresAt(date('Y-m-d H:i:s', $now + 86400 * 30));
//            return 'hola';
//        }
//
//        return parent::save($conn);
//    }
}
