<?php

/**
 * TipoLicenciaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoLicenciaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoLicenciaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoLicencia');
    }
}