<?php

/**
 * TramiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TramiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TramiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tramite');
    }
}