<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $nombres
 * @property string $apellido_paterno
 * @property string $apellido_materno
 * @property timestamp $fecha_nacimiento
 * @property string $direccion
 * @property string $telefono
 * @property string $telefono_celular
 * @property string $estado_civil
 * @property sfGuardUser $User
 * 
 * @method integer            getId()               Returns the current record's "id" value
 * @method integer            getUserId()           Returns the current record's "user_id" value
 * @method string             getNombres()          Returns the current record's "nombres" value
 * @method string             getApellidoPaterno()  Returns the current record's "apellido_paterno" value
 * @method string             getApellidoMaterno()  Returns the current record's "apellido_materno" value
 * @method timestamp          getFechaNacimiento()  Returns the current record's "fecha_nacimiento" value
 * @method string             getDireccion()        Returns the current record's "direccion" value
 * @method string             getTelefono()         Returns the current record's "telefono" value
 * @method string             getTelefonoCelular()  Returns the current record's "telefono_celular" value
 * @method string             getEstadoCivil()      Returns the current record's "estado_civil" value
 * @method sfGuardUser        getUser()             Returns the current record's "User" value
 * @method sfGuardUserProfile setId()               Sets the current record's "id" value
 * @method sfGuardUserProfile setUserId()           Sets the current record's "user_id" value
 * @method sfGuardUserProfile setNombres()          Sets the current record's "nombres" value
 * @method sfGuardUserProfile setApellidoPaterno()  Sets the current record's "apellido_paterno" value
 * @method sfGuardUserProfile setApellidoMaterno()  Sets the current record's "apellido_materno" value
 * @method sfGuardUserProfile setFechaNacimiento()  Sets the current record's "fecha_nacimiento" value
 * @method sfGuardUserProfile setDireccion()        Sets the current record's "direccion" value
 * @method sfGuardUserProfile setTelefono()         Sets the current record's "telefono" value
 * @method sfGuardUserProfile setTelefonoCelular()  Sets the current record's "telefono_celular" value
 * @method sfGuardUserProfile setEstadoCivil()      Sets the current record's "estado_civil" value
 * @method sfGuardUserProfile setUser()             Sets the current record's "User" value
 * 
 * @package    agenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('id', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 5,
             ));
        $this->hasColumn('user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('nombres', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('apellido_paterno', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('apellido_materno', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('fecha_nacimiento', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('direccion', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('telefono', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('telefono_celular', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('estado_civil', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}