ClaseAnterior:
  connection: doctrine
  tableName: clase_anterior
  columns:
    id_solicitud:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_tipo_licencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    TipoLicencia:
      local: id_tipo_licencia
      foreign: id_tipo_licencia
      type: one
    SolicitudLicencia:
      local: id_solicitud
      foreign: id_solicitud
      type: one
DiaNoLaboral:
  connection: doctrine
  tableName: dia_no_laboral
  columns:
    id_dia_no_laboral:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    user_id:
      type: integer(5)
      notnull: true
    fecha_no_laboral:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    User:
      class: sfGuardUser
      foreign: id
      local: user_id
      type: one
Hora:
  connection: doctrine
  tableName: hora
  columns:
    id_hora:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      notnull: true
      autoincrement: true
    id_solicitud:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_hora:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    hora_ini:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tipo:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Pago:
  connection: doctrine
  tableName: pago
  columns:
    id_pago:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_solicitud:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    monto:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    SolicitudLicencia:
      local: id_solicitud
      foreign: id_solicitud
      type: one







SolicitudLicencia:
  connection: doctrine
  tableName: solicitud_licencia
  columns:
    id_solicitud:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_tramite:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    rut:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user_id:
      type: integer(5)
      notnull: true
    id_pago:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_hora:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_tipo_licencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    estado:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_ultimo_control:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_control:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    restriccion:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    comuna_anterior:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    porta_licencia:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    motivo_no_porta_licencia:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    es_donante:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    TipoLicencia:
      local: id_tipo_licencia
      foreign: id_tipo_licencia
      type: one
    Tramite:
      local: id_tramite
      foreign: id_tramite
      type: one
    Hora:
      local: id_hora
      foreign: id_hora
      type: one
    User:
      class: sfGuardUser
      foreign: id
      local: user_id
      type: one
    Pago:
      local: id_pago
      foreign: id_pago
      type: one
    ClaseAnterior:
      local: id_solicitud
      foreign: id_solicitud
      type: many
      
      
      
      
      
ConjuntoExamenes:
  connection: doctrine
  tableName: conjunto_examenes
  columns:
    id_tramite:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_examen:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_tipo_licencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    TipoLicencia:
      local: id_tipo_licencia
      foreign: id_tipo_licencia
      type: one
    Tramite:
      local: id_tramite
      foreign: id_tramite
      type: one
    Examen:
      local: id_examen
      foreign: id_examen
      type: one
ConjuntoRequisitos:
  connection: doctrine
  tableName: conjunto_requisitos
  columns:
    id_requisito:
      type: integer(4)
      fixed: falsemany
      unsigned: false
      primary: true
      autoincrement: false
    id_tramite:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_tipo_licencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    TipoLicencia:
      local: id_tipo_licencia
      foreign: id_tipo_licencia
      type: one
    Requisito:
      local: id_requisito
      foreign: id_requisito
      type: one
    Tramite:
      local: id_tramite
      foreign: id_tramite
      type: one
Examen:
  connection: doctrine
  tableName: examen
  columns:
    id_examen:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre_examen:
      type: string(40)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion_examen:
      type: string(512)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ConjuntoExamenes:
      local: id_examen
      foreign: id_examen
      type: many
Requisito:
  connection: doctrine
  tableName: requisito
  columns:
    id_requisito:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre_requisito:
      type: string(40)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion_requisito:
      type: string(512)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ConjuntoRequisitos:
      local: id_requisito
      foreign: id_requisito
      type: many
TipoLicencia:
  connection: doctrine
  tableName: tipo_licencia
  columns:
    id_tipo_licencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre_tipo_licencia:
      type: string(20)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion_tipo_licencia:
      type: string(512)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ConjuntoExamenes:
      local: id_tipo_licencia
      foreign: id_tipo_licencia
      type: many
    ConjuntoRequisitos:
      local: id_tipo_licencia
      foreign: id_tipo_licencia
      type: many
Tramite:
  connection: doctrine
  tableName: tramite
  columns:
    id_tramite:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre_tramite:
      type: string(40)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    descripcion_tramite:
      type: string(512)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ConjuntoExamenes:
      local: id_tramite
      foreign: id_tramite
      type: many
    ConjuntoRequisitos:
      local: id_tramite
      foreign: id_tramite
      type: many